library(dplyr)
library(readr)
y_train <- read_table("./y_train.txt", col_names = F)
y_test <- read_table("./y_test.txt", col_names = F)
x_train <- read_table("./X_train.txt", col_names = FALSE)
x_test <- read_table("./X_test.txt", col_names = FALSE)
features <- read_lines("./features.txt")
features <- gsub(" ", "_", features)
features <- gsub("-", "_", features)
features <- gsub("()", "", features, fixed = TRUE)
names(x_test) <- features
names(x_train) <- features
x_test <- mutate(x_test, test_labels = y_test, .before = 1)
x_train <- mutate(x_train, test_labels = y_train, .before = 1)
x_merged <- rbind(x_train,x_test)
keep <- grepl("mean|std|test_labels", names(x_merged), ignore.case = TRUE)
x_extract <- x_merged[,keep]
x_extract[1] <- lapply(x_extract$test_labels, as.character)
x_extract$test_labels <- factor(x_extract$test_labels,
                                levels = c("1", "2", "3", "4", "5", "6"),
                                labels = c("walking", "walking_upstairs", "walking_downstairs", "sitting", "standing", "laying")
                                )
subject_train <- read_table("./subject_train.txt")
subject_test <- read_table("./subject_test.txt")
subject_train <- pull(subject_train, 1)
subject_test <- pull(subject_test, 1)
subject_bind <- append(subject_train,subject_test)
subject_bind <- append(subject_bind, c(24,24))
x_extract <- mutate(x_extract, subject_labels = subject_bind, .before = 1)
x_grouped <- mutate(x_extract, groups = paste(x_extract$subject_labels, x_extract$test_labels, sep = "_"), .before = 3)
x_grouped <- group_by(x_grouped, groups)
names(x_grouped) <- gsub("^(\\d)+_", "", names(x_grouped))
x_grouped <- mutate(x_grouped, subject_labels = as.character(subject_labels))
summ <- summarise_if(x_grouped,is.numeric, mean)